//! Markdown readiness report. Board-ready, GitHub-flavoured Markdown.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use time::format_description::well_known::Rfc3339;
use time::OffsetDateTime;

use crate::model::asset::{CryptoAsset, PqcStatus};
use crate::scoring;
use crate::storage;
use crate::workspace::Workspace;

pub fn write(ws: &Workspace, out: &Path) -> Result<()> {
    let systems = storage::load_systems(ws)?;
    let inventory = storage::load_inventory(ws)?;
    let plans = storage::list_plans(ws)?;
    let registry = crate::vendor::load_merged(ws)?;
    let today = OffsetDateTime::now_utc();

    let mut scored: Vec<(CryptoAsset, crate::model::score::RiskScore)> = inventory
        .into_iter()
        .map(|a| {
            let sys = a
                .system_id
                .and_then(|id| systems.iter().find(|s| s.id == id));
            let s = scoring::score_asset(&a, sys, today);
            (a, s)
        })
        .collect();
    scored.sort_by(|a, b| {
        b.1.priority
            .partial_cmp(&a.1.priority)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    let total = scored.len();
    let vulnerable = scored
        .iter()
        .filter(|(a, _)| matches!(a.pqc_status, PqcStatus::Vulnerable | PqcStatus::Unknown))
        .count();
    let vulnerable_pct = if total == 0 {
        0.0
    } else {
        (vulnerable as f32) * 100.0 / (total as f32)
    };

    let mut tier_counts: BTreeMap<u8, usize> = BTreeMap::new();
    for (_, s) in &scored {
        *tier_counts.entry(s.triage_tier).or_default() += 1;
    }
    let mut status_counts: BTreeMap<&'static str, usize> = BTreeMap::new();
    for (a, _) in &scored {
        let k = match a.pqc_status {
            PqcStatus::Vulnerable => "vulnerable",
            PqcStatus::Hybrid => "hybrid",
            PqcStatus::Resistant => "resistant",
            PqcStatus::SymmetricOk => "symmetric_ok",
            PqcStatus::Unknown => "unknown",
        };
        *status_counts.entry(k).or_default() += 1;
    }

    let mut md = String::new();
    md.push_str("# Boab PQC Readiness Report\n\n");
    md.push_str(&format!(
        "Generated by Boab {} at {}.\n\n",
        env!("CARGO_PKG_VERSION"),
        today.format(&Rfc3339).unwrap_or_default()
    ));

    md.push_str("## Executive summary\n\n");
    md.push_str(&format!("- Total inventory: **{}** assets\n", total));
    md.push_str(&format!(
        "- Quantum-vulnerable or unknown: **{} ({:.1}%)**\n",
        vulnerable, vulnerable_pct
    ));
    md.push_str(&format!("- Systems in scope: **{}**\n", systems.len()));
    md.push_str(&format!("- Plans on file: **{}**\n\n", plans.len()));

    md.push_str("## ASD LATICE phase status\n\n");
    md.push_str("| Milestone | Year | Status |\n");
    md.push_str("|-----------|------|--------|\n");
    md.push_str(&format!(
        "| Refined transition plan | 2026 | {} |\n",
        if plans.iter().any(|p| p.milestone.year() == 2026) {
            "plan drafted"
        } else {
            "plan outstanding"
        }
    ));
    md.push_str(&format!(
        "| Implementation begins | 2028 | {} |\n",
        if plans.iter().any(|p| p.milestone.year() == 2028) {
            "plan drafted"
        } else {
            "plan outstanding"
        }
    ));
    md.push_str(&format!(
        "| Implementation complete | 2030 | {} |\n\n",
        if plans.iter().any(|p| p.milestone.year() == 2030) {
            "plan drafted"
        } else {
            "plan outstanding"
        }
    ));

    md.push_str("## Top 25 priority assets\n\n");
    md.push_str("| # | Name | Algorithm | PQC | Priority | Tier | Recommended action |\n");
    md.push_str("|---|------|-----------|-----|----------|------|--------------------|\n");
    for (i, (asset, score)) in scored.iter().take(25).enumerate() {
        md.push_str(&format!(
            "| {} | {} | {} | {} | {:.1} | {} | {} |\n",
            i + 1,
            escape_md(&asset.name),
            escape_md(&asset.algorithm_name),
            pqc_status_str(asset.pqc_status),
            score.priority,
            score.triage_tier,
            escape_md(&score.recommended_action)
        ));
    }
    md.push('\n');

    md.push_str("## Triage tier distribution\n\n");
    md.push_str("| Tier | Count |\n|------|-------|\n");
    for (tier, count) in &tier_counts {
        md.push_str(&format!("| {} | {} |\n", tier, count));
    }
    md.push('\n');

    md.push_str("## PQC status distribution\n\n");
    md.push_str("| Status | Count |\n|--------|-------|\n");
    for (k, v) in &status_counts {
        md.push_str(&format!("| {} | {} |\n", k, v));
    }
    md.push('\n');

    md.push_str("## Vendor PQC dependency summary\n\n");
    md.push_str("| Vendor | Product | PQC | Target |\n");
    md.push_str("|--------|---------|-----|--------|\n");
    for e in &registry.entries {
        md.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            escape_md(&e.vendor),
            escape_md(&e.product),
            pqc_status_str(e.pqc_status),
            escape_md(e.target_date.as_deref().unwrap_or("-"))
        ));
    }
    md.push('\n');

    md.push_str("## Plans on file\n\n");
    if plans.is_empty() {
        md.push_str("(no plans generated yet)\n\n");
    } else {
        md.push_str("| Plan | Milestone | Items | Generated |\n");
        md.push_str("|------|-----------|-------|-----------|\n");
        for p in &plans {
            md.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                escape_md(&p.name),
                p.milestone.year(),
                p.items.len(),
                p.generated_at.format(&Rfc3339).unwrap_or_default()
            ));
        }
        md.push('\n');
    }

    md.push_str("## Methodology\n\n");
    md.push_str("Boab uses the ASD LATICE rubric. The priority score is computed as:\n\n");
    md.push_str(
        "priority = round(algo_vuln * 0.30 + hndl * 0.30 + data_sens * 0.15 + sys_crit * 0.15 + mig_diff * 0.10, 1)\n\n",
    );
    md.push_str(
        "Triage tier 1 indicates an asset that must be migrated within the 2028 milestone window. Tier 2 fits comfortably inside the 2028 milestone, tier 3 within the 2029 to 2030 window, and tier 4 requires monitoring only.\n\n",
    );
    md.push_str(
        "Refer to the ASD Information Security Manual for control mappings. Boab does not map to specific ISM control IDs in v1; that work is on the v1.1 backlog.\n\n",
    );

    md.push_str(&format!(
        "---\n\nGenerated by Boab {}.\n",
        env!("CARGO_PKG_VERSION")
    ));

    if let Some(parent) = out.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(out, md).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

fn pqc_status_str(s: PqcStatus) -> &'static str {
    match s {
        PqcStatus::Vulnerable => "vulnerable",
        PqcStatus::Hybrid => "hybrid",
        PqcStatus::Resistant => "resistant",
        PqcStatus::SymmetricOk => "symmetric_ok",
        PqcStatus::Unknown => "unknown",
    }
}

fn escape_md(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}
